name: DevSecOps-Netflix-Project

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: DevSecOps-Netflix-Project
          projectKey: DevSecOps-Netflix-Project


    
    